//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Core.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfrastructureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfrastructureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Core.Infrastructure.InfrastructureResources", typeof(InfrastructureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GetAssembly] : could not load assembly &apos;{0}&apos; / exception = {1}.
        /// </summary>
        public static string AssemblyLoadException {
            get {
                return ResourceManager.GetString("AssemblyLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration item &apos;{0}&apos; is specified but empty.  Using the specified default &apos;{1}&apos;..
        /// </summary>
        public static string ConfigurationItemEmptyUsingDefault {
            get {
                return ResourceManager.GetString("ConfigurationItemEmptyUsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application setting &apos;{0}&apos; is missing or has an empty value..
        /// </summary>
        public static string ConfigurationItemMissing {
            get {
                return ResourceManager.GetString("ConfigurationItemMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration item not specified - using default.
        /// </summary>
        public static string ConfigurationItemMissingUsingDefault {
            get {
                return ResourceManager.GetString("ConfigurationItemMissingUsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAssemblies() called with ShadowCopyFiles = &apos;{0}&apos;..
        /// </summary>
        public static string DebugGetAssemblies {
            get {
                return ResourceManager.GetString("DebugGetAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; has no default constructor..
        /// </summary>
        public static string DefaultConstructorRequired {
            get {
                return ResourceManager.GetString("DefaultConstructorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IComponentResolver implementation returned the same pipeline instance of type &apos;{0}&apos;.  Since pipelines are not stateless that cannot be shared.  Please register the pipeline types as transient..
        /// </summary>
        public static string DuplicatePipelineInstanceException {
            get {
                return ResourceManager.GetString("DuplicatePipelineInstanceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An implementation type has already been registered for dependency type &apos;{0}&apos;. .
        /// </summary>
        public static string DuplicateTypeRegistrationException {
            get {
                return ResourceManager.GetString("DuplicateTypeRegistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string with name &apos;{0}&apos; may not be empty..
        /// </summary>
        public static string EmptyStringException {
            get {
                return ResourceManager.GetString("EmptyStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering pipeline stage &apos;{0}&apos;..
        /// </summary>
        public static string EnteringPipelineStage {
            get {
                return ResourceManager.GetString("EnteringPipelineStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing pipeline &apos;{0}&apos;..
        /// </summary>
        public static string ExecutingPipeline {
            get {
                return ResourceManager.GetString("ExecutingPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First chance exception handled by pipeline: {0}.
        /// </summary>
        public static string FirstChanceExceptionHandledByPipeline {
            get {
                return ResourceManager.GetString("FirstChanceExceptionHandledByPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no argument with name &apos;{0}&apos;..
        /// </summary>
        public static string InvalidArgumentException {
            get {
                return ResourceManager.GetString("InvalidArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type &apos;{0}&apos; used with Guard possibly does not have a constructor that takes 1 string parameter (message).  Exception reported: {1}.
        /// </summary>
        public static string InvalidGuardExceptionType {
            get {
                return ResourceManager.GetString("InvalidGuardExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an unnamed registration for service type &apos;{0}&apos;..
        /// </summary>
        public static string InvalidNamedTypeRegistrationException {
            get {
                return ResourceManager.GetString("InvalidNamedTypeRegistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression algorithm &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string MissingCompressionAlgorithmException {
            get {
                return ResourceManager.GetString("MissingCompressionAlgorithmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption algorithm &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string MissingEncryptionAlgorithmException {
            get {
                return ResourceManager.GetString("MissingEncryptionAlgorithmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get type &apos;{0}&apos;.  Ensure that you have a fully qualified type: &apos;FullName, Assembly&apos;..
        /// </summary>
        public static string MissingTypeException {
            get {
                return ResourceManager.GetString("MissingTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required dependency of type &apos;{0}&apos; is null..
        /// </summary>
        public static string NullDependencyException {
            get {
                return ResourceManager.GetString("NullDependencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IComponentResolver implementation returned null for pipeline of type &apos;{0}&apos;..
        /// </summary>
        public static string NullPipelineException {
            get {
                return ResourceManager.GetString("NullPipelineException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value with name &apos;{0}&apos; may not be null..
        /// </summary>
        public static string NullValueException {
            get {
                return ResourceManager.GetString("NullValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline stage &apos;{0}&apos; has no event of type &apos;{1}&apos;..
        /// </summary>
        public static string PipelineStageEventNotRegistered {
            get {
                return ResourceManager.GetString("PipelineStageEventNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no pipeline stage with a name of &apos;{0}&apos;..
        /// </summary>
        public static string PipelineStageNotFound {
            get {
                return ResourceManager.GetString("PipelineStageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread executing] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string ProcessorExecuting {
            get {
                return ResourceManager.GetString("ProcessorExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread active] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string ProcessorThreadActive {
            get {
                return ResourceManager.GetString("ProcessorThreadActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread starting] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string ProcessorThreadStarting {
            get {
                return ResourceManager.GetString("ProcessorThreadStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread stopped] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string ProcessorThreadStopped {
            get {
                return ResourceManager.GetString("ProcessorThreadStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread stopping] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string ProcessorThreadStopping {
            get {
                return ResourceManager.GetString("ProcessorThreadStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to assign a value to &apos;{0}&apos; but it has already been assigned a value..
        /// </summary>
        public static string ReassignmentException {
            get {
                return ResourceManager.GetString("ReassignmentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type &apos;{0}&apos; since there is no single implementation..
        /// </summary>
        public static string ResolveException {
            get {
                return ResourceManager.GetString("ResolveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no registration named &apos;{0}&apos; for service type &apos;{1}&apos;..
        /// </summary>
        public static string ResolveNameException {
            get {
                return ResourceManager.GetString("ResolveNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] : Stream position is not 0 but seek is not permitted..
        /// </summary>
        public static string StreamCannotSeek {
            get {
                return ResourceManager.GetString("StreamCannotSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String duration contains invalid items &apos;{0}&apos;..
        /// </summary>
        public static string StringDurationFormatError {
            get {
                return ResourceManager.GetString("StringDurationFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue handler configuration requires thread count of at least 1.  The input queue can not be processed..
        /// </summary>
        public static string ThreadCountZeroException {
            get {
                return ResourceManager.GetString("ThreadCountZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread pool &apos;{0}&apos; has {1} successfully..
        /// </summary>
        public static string ThreadPoolStatusChange {
            get {
                return ResourceManager.GetString("ThreadPoolStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving all types from from assembly &apos;{0}&apos;..
        /// </summary>
        public static string TraceGetTypesFromAssembly {
            get {
                return ResourceManager.GetString("TraceGetTypesFromAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to &apos;{0}.{1}&apos; already contains an active TransactionScope..
        /// </summary>
        public static string TransactionAlreadyStartedException {
            get {
                return ResourceManager.GetString("TransactionAlreadyStartedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TripleDES section in the application configuration file may not have an empty value for the &apos;key&apos; attribute..
        /// </summary>
        public static string TripleDESKeyMissing {
            get {
                return ResourceManager.GetString("TripleDESKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use TripleDES cryptography you need to add the &apos;tripleDES&apos; section to the application configuration file.  Remember to add the section handler..
        /// </summary>
        public static string TripleDESSectionMissing {
            get {
                return ResourceManager.GetString("TripleDESSectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No implementation type has been registered for dependency type &apos;{0}&apos;..
        /// </summary>
        public static string TypeNotRegisteredException {
            get {
                return ResourceManager.GetString("TypeNotRegisteredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register service type &apos;{0}&apos; as the implementation type &apos;{1}&apos; is not of that type..
        /// </summary>
        public static string UnassignableTypeRegistrationException {
            get {
                return ResourceManager.GetString("UnassignableTypeRegistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception during event &apos;{0}&apos;: {1}.
        /// </summary>
        public static string UnhandledPipelineException {
            get {
                return ResourceManager.GetString("UnhandledPipelineException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum type &apos;{0}&apos; does not contain a value &apos;{1}&apos;..
        /// </summary>
        public static string UnknownEnumValueException {
            get {
                return ResourceManager.GetString("UnknownEnumValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raising pipeline event &apos;{0}&apos; in stage &apos;{1}&apos; for observer &apos;{2}&apos;..
        /// </summary>
        public static string VerboseRaisingPipelineEvent {
            get {
                return ResourceManager.GetString("VerboseRaisingPipelineEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionScope (&apos;{0}&apos;) using ambient transaction..
        /// </summary>
        public static string VerboseTransactionScopeAmbient {
            get {
                return ResourceManager.GetString("VerboseTransactionScopeAmbient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionScope (&apos;{0}&apos;) using ambient transaction has completed..
        /// </summary>
        public static string VerboseTransactionScopeAmbientCompleted {
            get {
                return ResourceManager.GetString("VerboseTransactionScopeAmbientCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionScope (&apos;{0}&apos;) has completed..
        /// </summary>
        public static string VerboseTransactionScopeCompleted {
            get {
                return ResourceManager.GetString("VerboseTransactionScopeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionScope (&apos;{0}&apos;) created with isolation level &apos;{1}&apos; and timeout of &apos;{2}&apos;..
        /// </summary>
        public static string VerboseTransactionScopeCreated {
            get {
                return ResourceManager.GetString("VerboseTransactionScopeCreated", resourceCulture);
            }
        }
    }
}
